### ISSUE TITLE
Support options.type

### ISSUE THREAD

**Issue by tmcdonnell87** [najaxjs/najax#20]
$.ajax supports a 'type' parameter as an alias for method (http://api.jquery.com/jquery.ajax/). Najax should support this, as some frameworks (e.g. Backbone) generate ajax options with this as the parameter name. 

It's incredibly easy: just add 
`options.method = options.method || options.type;`
to the beginning of the request function. 

Awesome module - thanks for the help!

**Comment by alanclarke** [comment]
hey @tmcdonnell87, sounds great, would you be willing to submit a pr for this feature?

**Comment by tmcdonnell87** [comment]
PR #21

**Comment by tmcdonnell87** [comment]
@alanclarke any update?

**Comment by alanclarke** [comment]
thanks @tmcdonnell87 - merged!

**Comment by Xazzzi** [comment]
Someone shoult update npm package to include this change there.

**Comment by alanclarke** [comment]
done!

**Comment by Xazzzi** [comment]
Actually, issue is still there.
We have `var defaults = {method: 'GET', ...}` in `najax.js`, that is used later: 
```var o = _.extend({}, defaults, parseOptions(uri, options, callback))```
This leads to setting `o.method` even when we had not `method` in original options.
Later, when `o.method = o.method || o.type` is performed, `o.type` will never be used, because `o.method` is already set.
I suggest moving this check into `parse-options.js` at line 17 just before return:
```opts.method = opts.method || opts.type;```
This will fix the issue. 
Don't forget to bump version number/update npm pakage =)
